# -*- coding: utf-8 -*-
"""Untitled45.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NjNmCgJyw5qhuyDN_A4P0VMElVzA3N1A
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv('Melbourne_housing_FULL.csv')
df

df.nunique()

df.shape

cols_to_use = ['Suburb', 'Rooms','Type','Method','SellerG','Regionname','Propertycount','Distance','CouncilArea','Bedroom2','Bathroom','Car','Landsize','BuildingArea','Price']
df = df[cols_to_use]
df

df.shape()

df.isnull().sum()

cols_to_fill_zero = ['Propertycount','Distance','Bedroom2','Bathroom','Car']
df[cols_to_fill_zero] = df[cols_to_fill_zero].fillna(0)
df.isna().sum()

df['Landsize'] = df['Landsize'].fillna(df.Landsize.mean())
df['BuildingArea'] = df['BuildingArea'].fillna(df.BuildingArea.mean())

df.isna().sum()

df.dropna(inplace = True)
df.isna().sum()

df = pd.get_dummies(df, drop_first = True)
df

x = df.drop('Price', axis = 1)
y = df['Price']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X_train, y_train)
reg.score(X_test, y_test)

from sklearn import linear_model
lasso_reg = linear_model.Lasso(alpha = 50, max_iter = 100, tol = 0.1)
lasso_reg.fit(X_train, y_train)

lasso_reg.score(X_test, y_test)

